name: Push-to-EC2

# Trigger deployment only on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Install Apache and Deploy
        run: |
          # Update the following variables with your specific values
          TARGET_DIR="${{ secrets.TARGET_DIR }}"

          # Install Apache (if not already installed)
          sudo apt-get update
          sudo apt-get install -y apache2

          # Move your web application files to the Apache document root
          sudo mv $GITHUB_WORKSPACE/* /var/www/html/

          # Restart Apache to apply changes
          sudo systemctl restart apache2
        env:
          TARGET_DIR: ${{ secrets.TARGET_DIR }}
